### PR TITLE
Add curl client in README to generate sample data.

### PR DESCRIPTION
**Pull request by Amiedeep**
This pull request has the following features:

1. It adds a reference to the `curl` command used to generate data in README.
2. It adds an example FluentD configuration file to read data from the file system and push to elastic search.

NOTE: For using FluentD file system configuration file - you need to change the docker-compose file accordingly. I have added a few instructions in comments in fluentd_copy_files.conf file.

### CODE REVIEW

**Comment by Amiedeep** [comment]
@giefferre

**Review by giefferre — COMMENTED** [review]
@Amiedeep thanks for your improvement, this is really appreciated.

Can you just edit the body of the pull request to better explain the modifications you've done so to let a future reader better understand the change history? Many thanks in advance.

**Comment by Amiedeep** [comment]
@giefferre I have briefed about the changes in the pull request. 

Initially, I was intended to only update readme with the curl command. However, I added another example file in the examples folder later.

**Review by giefferre — APPROVED** [review]
👍

**Comment by Amiedeep** [comment]
@giefferre  The changes are not merged with master.

**Pull request merged**
